[Variables]
;Set up your GPU here.
GPUTempIndex=3
GPUCoreLoadIndex=7
GPUClockIndex=5
GPUMemoryClockIndex=6
GPUMemoryUsageIndex=8
GPUPowerIndex=4


;For the BarsMeters
MinTemperature = 42
MaxTemperature = 100
MinClock = 0
MaxClock = 2040
MinMemoryClock = 0
MaxMemoryClock = 2250
MinPower = 0
MaxPower = 175
MinActivity = 0
MaxActivity = 100
MinMemorySize = 0
MaxMemorySize = 16376
GPUName=NVIDIA RTX 4090